version: '3.8'

services:
  app:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gamehub
      POSTGRES_PASSWORD: gamehub_password
      POSTGRES_DB: gamehub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: